spring.application.name=spring-shopping
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:shopping;DB_CLOSE_DELAY=-1

client.purgomalum.base-url=http://www.purgomalum.com
