spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  thymeleaf:
    cache: false
  sql:
    init:
      mode: embedded
  messages:
    basename: messages, errors
cache:
  eviction:
    fixed-rate: 60000
currency-layer:
  secret-key: ${CURRENCY_LAYER_SECRET_KEY}
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: 86400000

---

spring:
  config:
    activate:
      on-profile: no-init-test
  sql:
    init:
      mode: never
