spring:
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/spring_shopping
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password

security:
  jwt:
    token:
      secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
      expire-time: 3600000

api:
  url: "http://api.currencylayer.com/live"
  quotes: quotes
  source: USD
  target: KRW
  accessKey: ${API_ACCESS_KEY}
