spring:
  profiles:
    active: default
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

security:
  jwt:
    secret-key: 57aaefa3f13fcbdf27b6a06b21a9383bba4d03c6c2d1074c806513b8c8dd1fb0
    expiration: 3600000

secret:
  currency:
    access_key: ${CURRENCY_KEY}
    url: http://api.currencylayer.com/live?currencies=KRW&access_key=
