create table product (
     id bigint generated by default as identity,
     file_name varchar(255),
     image_store_type varchar(255),
     name varchar(255),
     amount numeric(19,2),
     primary key (id)
);

create table Member (
     id bigint generated by default as identity,
     email varchar(255),
     password varchar(255),
     primary key (id)
);
