drop table if exists cart_item;
drop table if exists product;
drop table if exists member;
drop table if exists order_item;
drop table if exists orders;

create table if not exists product (
     id bigint generated by default as identity,
     image_path varchar(255),
     name varchar(255),
     amount numeric(19,2),
     primary key (id)
);

create table if not exists member (
    id bigint generated by default as identity,
    email varchar(255),
    password varchar(255),
    primary key (id)
);

create table if not exists cart_item (
   id bigint generated by default as identity,
   member_id bigint,
   product_id bigint,
   product_name varchar(255),
   amount numeric(19,2),
   quantity integer not null,
   primary key (id),
    FOREIGN KEY (member_id) REFERENCES member(id),
    FOREIGN KEY (product_id) REFERENCES product(id)
);

create table if not exists orders (
    id bigint generated by default as identity,
    member_id bigint,
    primary key (id)
);

create table if not exists order_item (
    id bigint generated by default as identity,
    product_id bigint,
    image_path varchar(255),
    product_name varchar(255),
    amount numeric(19,2),
    quantity integer,
    orders_id bigint,
    primary key (id),
    foreign key (orders_id) references Orders(id)
);
